// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUaBY3dyCTIKQ0JHpZGIv2KlYMmYNz80',
    appId: '1:771567808915:web:5eb64f8f1678af353c3866',
    messagingSenderId: '771567808915',
    projectId: 'newfirebase-b547a',
    authDomain: 'newfirebase-b547a.firebaseapp.com',
    storageBucket: 'newfirebase-b547a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnvPZDIe2SRWcPK1aruGvBwagp3LiCPkM',
    appId: '1:771567808915:android:1985218c466154803c3866',
    messagingSenderId: '771567808915',
    projectId: 'newfirebase-b547a',
    storageBucket: 'newfirebase-b547a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApxKZtK2dPUsz3AF2I_vKm2JpPweetIpc',
    appId: '1:771567808915:ios:95da576a18b33afb3c3866',
    messagingSenderId: '771567808915',
    projectId: 'newfirebase-b547a',
    storageBucket: 'newfirebase-b547a.firebasestorage.app',
    iosBundleId: 'com.example.newfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApxKZtK2dPUsz3AF2I_vKm2JpPweetIpc',
    appId: '1:771567808915:ios:95da576a18b33afb3c3866',
    messagingSenderId: '771567808915',
    projectId: 'newfirebase-b547a',
    storageBucket: 'newfirebase-b547a.firebasestorage.app',
    iosBundleId: 'com.example.newfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUaBY3dyCTIKQ0JHpZGIv2KlYMmYNz80',
    appId: '1:771567808915:web:eecb9fba24c801103c3866',
    messagingSenderId: '771567808915',
    projectId: 'newfirebase-b547a',
    authDomain: 'newfirebase-b547a.firebaseapp.com',
    storageBucket: 'newfirebase-b547a.firebasestorage.app',
  );
}
